"""Utility for computing first-error detection F1 from MIL annotation dumps."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Iterable


def parse_args() -> argparse.Namespace:
	parser = argparse.ArgumentParser(
		description=(
			"Compute first-error detection accuracy/F1 from an annotation JSONL file."
		)
	)
	parser.add_argument(
		"--annotation_file",
		type=Path,
		help=(
			"Path to eval_annotations.jsonl generated by MIL annotation_output."
		),
	)
	parser.add_argument(
		"--max-records",
		type=int,
		default=None,
		help="Only process the first N records (useful for spot checks).",
	)
	parser.add_argument(
		"--output_file",
        type=Path,
        default=None,
        help=(
            "Optional path to write metrics JSON output. If not provided, metrics will only be printed to stdout."
        ),
    )
	return parser.parse_args()


def first_error_index(labels: list[int]) -> int:
	"""Return the index of the first segment labeled as an error (label==0)."""

	for idx, label in enumerate(labels):
		if label == 0:
			return idx
	return len(labels)


def iter_records(path: Path, limit: int | None) -> Iterable[dict]:
	read = 0
	with path.open("r", encoding="utf-8") as handle:
		for line in handle:
			if limit is not None and read >= limit:
				break
			line = line.strip()
			if not line:
				continue
			read += 1
			yield json.loads(line)


def compute_metrics(records: Iterable[dict]) -> dict[str, float]:
	positive_acc = []
	negative_acc = []
	total = 0
	mismatched_lengths = 0

	for record in records:
		total += 1
		preds = record.get("segment_annotations") or []
		targets = record.get("segment_labels") or []
		if not preds or not targets:
			continue
		if len(preds) != len(targets):
			mismatched_lengths += 1
			length = min(len(preds), len(targets))
			preds = preds[:length]
			targets = targets[:length]

		# Mirror Trainer logic: compare first indices whose label is 0 (error).
		sentry = len(preds)
		pred_index = first_error_index(preds)
		target_index = first_error_index(targets)
		accuracy = 1.0 if pred_index == target_index else 0.0

		assert record.get("document_label") == (sum(targets) == len(targets)), "Document label should indicate whether all segments are correct (1) or if there's at least one error (0)."
		if record.get("document_label") == 1:
			positive_acc.append(accuracy)
		else:
			negative_acc.append(accuracy)

	metrics: dict[str, float] = {}
	if positive_acc:
		metrics["error_detection_positive_accuracy"] = sum(positive_acc) / len(
			positive_acc
		)
	if negative_acc:
		metrics["error_detection_negative_accuracy"] = sum(negative_acc) / len(
			negative_acc
		)
	if positive_acc and negative_acc:
		pos = metrics["error_detection_positive_accuracy"]
		neg = metrics["error_detection_negative_accuracy"]
		metrics["error_detection_f1"] = 200 * pos * neg / (pos + neg + 1e-8)
	metrics["processed_records"] = total
	metrics["mismatched_lengths"] = mismatched_lengths
	return metrics


def main() -> None:
	args = parse_args()
	if not args.annotation_file.exists():
		raise FileNotFoundError(f"No such file: {args.annotation_file}")
	metrics = compute_metrics(iter_records(args.annotation_file, args.max_records))
	if metrics.get("processed_records", 0) == 0:
		print("No usable records found.")
		return
	for key, value in metrics.items():
		if isinstance(value, float):
			print(f"{key}: {value:.6f}")
		else:
			print(f"{key}: {value}")
	if args.output_file:
		with args.output_file.open("w", encoding="utf-8") as handle:
			json.dump(metrics, handle, indent=4)
		print(f"Metrics written to {args.output_file}")


if __name__ == "__main__":
	main()
